### ISSUE TITLE
How is this supposed to be implemented?

### ISSUE THREAD

**Issue by carlosmarioroldan** [Wacom-Developer/signature-sdk-js#1]
I've been trying to use this SDK following the "Simple" demo but it has been pretty hard to get anything working. Am I missing something or do you really need to add a whole bunch of old third-party libraries to your project in order to use it. If so, this definitely needs some sort of abstraction that would facilitate the implementation.

![image](https://user-images.githubusercontent.com/67707877/155851675-184b28ac-9ea9-4e0e-8a80-0746f40f621e.png)

**Comment by Zwelc** [comment]
I tried downloading the old libraries that weren't included in the project and even that just leads to more errors instead of a working demo

**Comment by STGoodlandWacom** [comment]
Hi Carlos,

Thanks for posting and apologies for taking so long to get back to you. 

Unfortunately, we're unable to include the third-party libraries by default. Additional information on the libraries can be found in the README here: https://github.com/Wacom-Developer/signature-sdk-js/blob/main/sigCaptDialog/README.md

If you have additional questions, might I suggest posting your queries here? https://support.wacom.com/hc/en-us/requests/new 

Our support engineers are more active there and would be happy to provide more assistance.

Thanks for your query! 

Best regards,

Sam

**Comment by juan-garrido** [comment]
npm depencencies has been added to the project.
