### ISSUE TITLE
No compatible HID devices found with DTU-1141B connected

### ISSUE THREAD

**Issue by fagylalt** [Wacom-Developer/signature-sdk-js#10]
Dear devs,

i tried using the SDK, cloning this repo, getting the adequate files from wacom dev support and the keys, yet the software simple demo does not see my DTU-1141B as a compatible device?

I asked support, and they told me that the 1141B is supported for this SDK. Is it so?

Thank you in advance.

**Comment by sioux1977** [comment]
Wich operating system are you using? I am on Linux Mint (Ubuntu based distro) and i have modified /dev/hidraw* permission to get my device viewed by library...

**Comment by fagylalt** [comment]
Hey, i am using win11 at the moment, with the latest drivers.

**Comment by fagylalt** [comment]
so turns out, it does support it, but not as a hid device, but as a generic device.
