### ISSUE TITLE
Questions about the use of signature-sdk-js to prompt Invalid licence in offline environments.

### ISSUE THREAD

**Issue by HeyChong** [Wacom-Developer/signature-sdk-js#12]
I tried to run the demos in signature-sdk-js as described in the documentation. When I was in a networked environment, it could be run, but when I was offline, a pop-up window would prompt Invalid license.
Excuse me:

```
Const promise = mSigObj.setLicence (...);
Promise. then (...);
```

Does it need to be connected to the Internet to run successfully?
Looking forward to your reply, thank you!

**Comment by HeyChong** [comment]
By the way, if I want to use signal-sdk-js in an offline environment, how can I do it? Is there any solution? Thanks.

**Comment by STGoodlandWacom** [comment]
Hi @HeyChong ,

Thanks for reaching out. Networking is required for access to our licensing server. Offline solutions may be available depending on your use case. 

If you have further queries, please reach out via developer support here: https://developer-support.wacom.com/hc/en-us/requests/new
