### ISSUE TITLE
Remove watermark

### ISSUE THREAD

**Issue by adit-gudhel** [Wacom-Developer/signature-sdk-js#13]
How to remove signature watermark and how to use signature lite license instead of using evaluation license?

**Comment by STGoodlandWacom** [comment]
Hi Aditya,

The Lite license is supplied only for the Signature SDK for Windows. To remove the signature watermark, you will need to acquire a production license for the Signature SDK for JavaScript. Please contact your regional Wacom Sales representative to obtain a production license at https://developer.wacom.com/.

Thanks for your inquiry! For future inquiries, we recommend contacting Developer Support here: https://developer-support.wacom.com/hc/en-us/requests/new

Best regards,

Sam
