### ISSUE TITLE
Can't render image of the signature

### ISSUE THREAD

**Issue by mattiaz9** [Wacom-Developer/signature-sdk-js#2]
This is my code:
```ts
const image = await sigObj.renderBitmap(
      renderWidth,
      renderHeight,
      "image/png",
      "pen",
      "#000000",
      "transparent", // transparent
      0,
      0,
      renderFlags
)
```

I get this error: `Bad ink width`

**Comment by juan-garrido** [comment]
Where you put "pen" it should be the stroke size if you don't use WILL Ink SDK, or a JSON object with the definition of a tool, look at the existing demos for a concrete example of definig an inking tool.

**Comment by mattiaz9** [comment]
thank you @juan-garrido, that worked!
