### ISSUE TITLE
Dependencies missing in package.json

### ISSUE THREAD

**Issue by raubv0gel** [Wacom-Developer/signature-sdk-js#5]
There are much more dependencies used in [demos/simple/index.html](https://github.com/Wacom-Developer/signature-sdk-js/blob/f52fe5e82bd363793a1d36e363b9d99690532d43/demos/simple/index.html) than defined in [package.json](https://github.com/Wacom-Developer/signature-sdk-js/blob/f52fe5e82bd363793a1d36e363b9d99690532d43/package.json). See `rbush` or `js-ext` for example.

Hence, I cannot run the demo. 😕

**Comment by phobos04** [comment]
Same here. 
Thanks a lot for your cooperation.

**Comment by STGoodlandWacom** [comment]
Hi @raubv0gel , @phobos04 ,

Thanks for reaching out and apologies for the delay in response. 

If you're still having this issue, version 2 of the Signature SDK for JavaScript has been released, which doesn't rely on these dependencies. 

If you need assistance in upgrading from version 1 to version 2, a guide on how to upgrade can be viewed here: https://developer-docs.wacom.com/docs/sdk-for-signature/guides/javascript/v2/v2-upgrade/.
