### ISSUE TITLE
Problem for use wacom sdk js

### ISSUE THREAD

**Issue by chusmsanchez** [Wacom-Developer/signature-sdk-js#6]
Hi, I'm trying to use your wacom sdk js library, but I can't find the external libraries it needs to run.

Is it possible that you send me an example with all the repositories/libraries that are necessary for it to work? or a manual where to download and install the necessary repositories?

My testing url is: https://app.billtonic.com/wacom/demos/simple/index.html

Greetings.

**Comment by sioux1977** [comment]
Hi chusmsamchez, i have cloned this repository and after put into apache web server, i can run the 'simple' demo without any issue. I see your simple.js code and itsn't the same of this repository... i see lot of /node_modules/.. paths that are inexistent. Are you sure that you haven't modified any file?

**Comment by STGoodlandWacom** [comment]
Hi @chusmsanchez , @sioux1977 ,

Thanks for reaching out and apologies for the delay in response.

If you're still having this issue, version 2 of the Signature SDK for JavaScript has been released, which doesn't rely on these dependencies.

If you need assistance in upgrading from version 1 to version 2, a guide on how to upgrade can be viewed here: https://developer-docs.wacom.com/docs/sdk-for-signature/guides/javascript/v2/v2-upgrade/.

If you have further queries, support may be contacted here: https://developer-support.wacom.com/hc/en-us/requests/new.
