### ISSUE TITLE
STU-430V in serial mode but no code

### ISSUE THREAD

**Issue by chattago2002** [Wacom-Developer/signature-sdk-js#7]
Hi.
I'm trying to use this repo with a STU-430V in serial connection. As written at the end of [this documentation link](https://developer-support.wacom.com/hc/en-us/articles/9354527507351-STU-430V-Installation-for-Serial-operation), "a different type of connection needs to be made in the code." but I can't find how to do.
Where is the "serialConnect" function? In which file?
I can't find a complete example neither a good documentation from official Wacom channels (here in GitHub or [developer-support.wacom.com](https://developer-support.wacom.com/)).
Can someone help me to apply right changes and make my STU-430V able to capture signuters using a webapp and the SDK?
Thanks

**Comment by STGoodlandWacom** [comment]
Hi @chattago2002 , 

Thanks for reaching out, and sorry for the delay. 

If this issue is still affecting you, please raise a ticket at https://developer-support.wacom.com/hc/en-us/requests/new.
