### ISSUE TITLE
Not signature data in the image when set transparent background

### ISSUE THREAD

**Issue by filippopoggini** [Wacom-Developer/signature-sdk-js#8]
When I try the function `mSigObj.renderBitmap(...)` with argument `backgroundColor = '#FFFFFF00';` I could see a well-rendered image with transparent background but without metadata inside (who, why, date of signature, etc ).

The function `mSigObj.renderBitmap` works correctly only with background color without alpha.

**Comment by STGoodlandWacom** [comment]
Hi @filippopoggini  , 

Thanks for reaching out, and sorry for the delay. 

If this issue is still affecting you, please raise a ticket at https://developer-support.wacom.com/hc/en-us/requests/new.
